### ISSUE TITLE
Why is my sidebar empty?

### ISSUE THREAD

**Issue by idesign2018** [Nuked88/ComfyUI-N-Sidebar#7]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/42263070/a4eb5c78-cb75-44ea-8384-20f9f70021fd)
Why is my sidebar empty? Nothing at all?

I also restarted it and it’s still empty after opening it.

**Comment by RYG81** [comment]
Same for me.

**Comment by Nuked88** [comment]
Did you downloaded the last version? If so press Ctrl +Shift + J and make a screenshot of the log in the console

**Comment by RYG81** [comment]
Resolved, thank you

**Comment by randykoala** [comment]
I tried git pull and it says up to date but i still have this issue - was there a resolution? I also have aegisflow installed

**Comment by Nuked88** [comment]
Hi! Should be fixed now!

**Comment by randykoala** [comment]
Yes thanks alll working fine
